version: '3.8'

services:
  root_db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=oneplan
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123!
    restart: always
        
    ports:
      - "5432:5432"